    <option value="">--Please choose an option--</option>
    <option value="C1">C1</option>
    <option value="C2">C2</option>
    <option value="C3">C3</option>
    <option value="C4">C4</option>
    <option value="C8">C8</option>
    <option value="XFMR_Switcher">XFMR_Switcher</option>
    <option value="Cables">Cables</option>
    <option value="Preparacion">Preparacion</option>
    <option value="Almacen">Almacen</option>
    <option value="Celda7">Celda7</option>
    <option value="Patios_Rampas_Gerardo">Patios_Rampas_Gerardo</option>
    <option value="Patios_Rampas_Loreley">Patios_Rampas_Loreley</option>
    <option value="Mantenimiento">Mantenimiento</option>
    <option value="Quimicos">Quimicos</option>
    <option value="Ingenieria">Ingenieria</option>
    <option value="Chassis">Chassis</option>
    <option value="SMT">SMT</option>
    <option value="IQC">IQC</option>
    <option value="BURN_IN">BURN_IN</option>
    <option value="RMA">RMA</option>
    <option value="Patios_Frontal_Manuel">Patios_Frontal_Manuel</option>
    <option value="Patios_David">Patios_David</option>
    <option value="Patios_Miguel">Patios_Miguel</option>
    <option value="Patio_Jardin">Patio_Jardin</option>
    <option value="Patio_Pasillo_Acceso">Patio_Pasillo_Acceso</option>
    <option value="Patio_Estacionamientos">Patio_Estacionamientos</option>
    <option value="Celda_PCS">Celda PCS</option>
    <option value="XFMR_Toroides_Lineales">XFMR Toroides/Lineales</option>
    <option value="Cuarto_Harneses">Cuarto_Harneses</option>
